import React from "react";
import {
  Sparkles,
  Brain,
  Clock,
  Workflow,
  Database,
  Heart,
  Shield,
  TrendingUp,
  Brush,
  Users,
  CalendarDays,
  Layers,
  Target,
  Briefcase,
  Code,
  Bug,
  Activity,
  Scale,
  CheckCircle2,
  Video,
  Search,
  UserPlus,
  LogOut,
} from "lucide-react";

export const initialFolders = [
  { id: "all", name: "All Notes", color: "text-blue-500", isDefault: true },
  {
    id: "eng",
    name: "Engineering",
    color: "text-emerald-500",
    isDefault: false,
  },
  { id: "mkt", name: "Marketing", color: "text-purple-500", isDefault: false },
  {
    id: "personal",
    name: "Personal",
    color: "text-amber-500",
    isDefault: false,
  },
];

export const templateCategories = [
  "All",
  "General",
  "Education",
  "Business",
  "Engineering",
  "Healthcare",
  "Legal",
  "Creative",
  "HR",
];

export const templatesDB = [
  {
    id: 1,
    name: "AI Auto-Detect",
    category: "General",
    desc: "Let Spoly listen and automatically pick the best diagram format.",
    icon: <Sparkles size={24} />,
    theme: "purple",
  },
  {
    id: 11,
    name: "Daily Standup",
    category: "General",
    desc: "Track what was done, what's next, and blockers.",
    icon: <Users size={24} />,
    theme: "blue",
  },
  {
    id: 12,
    name: "Weekly Sync",
    category: "General",
    desc: "General meeting notes, action items, and parking lot.",
    icon: <CalendarDays size={24} />,
    theme: "emerald",
  },
  {
    id: 2,
    name: "Study Mind Map",
    category: "Education",
    desc: "Break down complex lectures into visual, branching concept maps.",
    icon: <Brain size={24} />,
    theme: "blue",
  },
  {
    id: 3,
    name: "Historical Timeline",
    category: "Education",
    desc: "Visualize dates, eras, and chronological events perfectly.",
    icon: <Clock size={24} />,
    theme: "amber",
  },
  {
    id: 13,
    name: "Flashcard Generator",
    category: "Education",
    desc: "Extract key terms and definitions for quick studying.",
    icon: <Layers size={24} />,
    theme: "rose",
  },
  {
    id: 14,
    name: "Math/Physics Proof",
    category: "Education",
    desc: "Step-by-step extraction of formulas and logical proofs.",
    icon: <Database size={24} />,
    theme: "purple",
  },
  {
    id: 8,
    name: "Sales Discovery Call",
    category: "Business",
    desc: "Map out BANT: Budget, Authority, Need, and Timeline insights.",
    icon: <TrendingUp size={24} />,
    theme: "blue",
  },
  {
    id: 15,
    name: "SWOT Analysis",
    category: "Business",
    desc: "Strengths, Weaknesses, Opportunities, and Threats grid.",
    icon: <Target size={24} />,
    theme: "amber",
  },
  {
    id: 16,
    name: "Client Onboarding",
    category: "Business",
    desc: "Capture project scope, deliverables, and initial timelines.",
    icon: <Briefcase size={24} />,
    theme: "emerald",
  },
  {
    id: 4,
    name: "Microservices",
    category: "Engineering",
    desc: "Map out decoupled services, gateways, and architecture.",
    icon: <Workflow size={24} />,
    theme: "blue",
  },
  {
    id: 5,
    name: "Database ERD",
    category: "Engineering",
    desc: "Auto-generate Entity-Relationship diagrams from context.",
    icon: <Database size={24} />,
    theme: "emerald",
  },
  {
    id: 17,
    name: "System Sequence Diagram",
    category: "Engineering",
    desc: "Track API calls, messages, and order of operations.",
    icon: <Code size={24} />,
    theme: "purple",
  },
  {
    id: 18,
    name: "Bug Triage",
    category: "Engineering",
    desc: "Log reproduction steps, expected behavior, and root cause.",
    icon: <Bug size={24} />,
    theme: "rose",
  },
  {
    id: 6,
    name: "Medical Consultation",
    category: "Healthcare",
    desc: "Extract patient symptoms, diagnoses, and medical prescriptions.",
    icon: <Heart size={24} />,
    theme: "emerald",
  },
  {
    id: 19,
    name: "SOAP Note",
    category: "Healthcare",
    desc: "Subjective, Objective, Assessment, and Plan documentation.",
    icon: <Activity size={24} />,
    theme: "blue",
  },
  {
    id: 20,
    name: "Therapy Session",
    category: "Healthcare",
    desc: "Track patient progress, mood shifts, and coping strategies.",
    icon: <Brain size={24} />,
    theme: "purple",
  },
  {
    id: 7,
    name: "Legal Contract Review",
    category: "Legal",
    desc: "Isolate clauses, liabilities, and core contractual obligations.",
    icon: <Shield size={24} />,
    theme: "amber",
  },
  {
    id: 21,
    name: "Deposition Summary",
    category: "Legal",
    desc: "Summarize witness testimonies and key evidentiary facts.",
    icon: <Scale size={24} />,
    theme: "blue",
  },
  {
    id: 22,
    name: "Compliance Audit",
    category: "Legal",
    desc: "Check regulatory requirements, violations, and action steps.",
    icon: <CheckCircle2 size={24} />,
    theme: "rose",
  },
  {
    id: 9,
    name: "Creative Brainstorm",
    category: "Creative",
    desc: "Summarize visual ideas, moodboard concepts, and design goals.",
    icon: <Brush size={24} />,
    theme: "purple",
  },
  {
    id: 23,
    name: "Video Storyboard",
    category: "Creative",
    desc: "Scene-by-scene breakdown of visual and audio cues.",
    icon: <Video size={24} />,
    theme: "amber",
  },
  {
    id: 24,
    name: "UX Research Interview",
    category: "Creative",
    desc: "Capture user pain points, behaviors, and feature requests.",
    icon: <Search size={24} />,
    theme: "emerald",
  },
  {
    id: 10,
    name: "HR Candidate Screen",
    category: "HR",
    desc: "Structure candidate background, strengths, weaknesses, and fit.",
    icon: <Users size={24} />,
    theme: "rose",
  },
  {
    id: 25,
    name: "Employee 1-on-1",
    category: "HR",
    desc: "Track career goals, blockers, and feedback.",
    icon: <UserPlus size={24} />,
    theme: "blue",
  },
  {
    id: 26,
    name: "Exit Interview",
    category: "HR",
    desc: "Capture reasons for leaving, company feedback, and transitions.",
    icon: <LogOut size={24} />,
    theme: "amber",
  },
];
